In [1]:
import numpy as np
import pandas as pd
import os
import shutil
from subprocess import Popen, PIPE
from IPython.display import clear_output
import time

In [2]:
PYPATH = '/home/shibal/anaconda3/envs/jasa/bin/python'
FILEPATH = '/home/shibal/Additive-Models-with-Structured-Interactions/SparseAMsWithInteractions/src/AMsWithInteractionsStrongHierarchy/AMsWithInteractionsStrongHierarchy-Synthetic-CV.py'
PATH = "/pool001/shibal/results-synthetic"

version = 13
# n = 100
r = 1.5
dist = 'skewed'

In [276]:
def make_bash_file(seed, version, dist, r):
    bash_folder_path = f"{PATH}/bashes/{dist}/v{version}_r{r}"
    bash_file_path = os.path.join(bash_folder_path, "seed{}.sh".format(seed))
    log_path = f"{PATH}/logs/{dist}/v{version}_r{r}/seed{seed}"
    os.makedirs(bash_folder_path,exist_ok=True)
    os.makedirs(log_path,exist_ok=True)
    with open(bash_file_path,"w") as f:
        f.write("#!/bin/bash\n")
        f.write("#SBATCH --cpus-per-task=4\n")
        f.write("#SBATCH --time=4-00:00\n")
        f.write("#SBATCH --mem=16G\n")
        f.write("#SBATCH -p sched_mit_sloan_batch\n")        
        f.write("#SBATCH --mail-type=FAIL\n")
        f.write("#SBATCH --mail-user=shibal@mit.edu\n")
        f.write(f"#SBATCH -o {log_path}/seed{seed}_%j.out\n")
        f.write(f"#SBATCH -e {log_path}/_seed{seed}_%j.err\n\n")
        f.write("module load sloan/python/modules/python-3.6/gurobipy/9.0.1\n\n")
        f.write(f"{PYPATH} -u {FILEPATH} --dist {dist} --seed {seed} --train_size {100} --version {version} --r {r} |& tee -a {log_path}/output.txt") 
        f.write(f"{PYPATH} -u {FILEPATH} --dist {dist} --seed {seed} --train_size {200} --version {version} --r {r} |& tee -a {log_path}/output.txt") 
        f.write(f"{PYPATH} -u {FILEPATH} --dist {dist} --seed {seed} --train_size {400} --version {version} --r {r} |& tee -a {log_path}/output.txt") 
    return bash_file_path


In [277]:
bash_files = []
seeds = np.arange(100)
for seed in seeds:
    bash_files.append(make_bash_file(seed, version, n, r))

In [278]:
torun = seeds
# torun = range(1,6)
submitted = []
print(len(torun))

100


In [279]:
exit_code = 1
for i, seed in enumerate(seeds):
    if i % 100 == 0:
        clear_output(wait=True)
    print(i)
    sh = make_bash_file(seed, version, n, r)
    while True:
        process = Popen(["sbatch",sh], stdout=PIPE)
        (output, err) = process.communicate()
        exit_code = process.wait()
        print(time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())),output,err)
        if exit_code == 0:
            print(sh,"submitted!")
            tmp_id = str(output)[-11:-3]
            print("job id:", tmp_id)
            submitted.append(tmp_id)
            break
        time.sleep(10000)

0
2022-10-29 08:07:53 b'Submitted batch job 45221349\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed0.sh submitted!
job id: 45221349
1
2022-10-29 08:07:53 b'Submitted batch job 45221350\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed1.sh submitted!
job id: 45221350
2
2022-10-29 08:07:53 b'Submitted batch job 45221351\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed2.sh submitted!
job id: 45221351
3
2022-10-29 08:07:53 b'Submitted batch job 45221352\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed3.sh submitted!
job id: 45221352
4
2022-10-29 08:07:54 b'Submitted batch job 45221353\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed4.sh submitted!
job id: 45221353
5
2022-10-29 08:07:54 b'Submitted batch job 45221354\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed5.sh submitted!
job id: 45221354
6
2022-10-29 08:07:54 b'Submitted batch job 45221355\n' None
/pool001/shibal/resul

2022-10-29 08:08:07 b'Submitted batch job 45221402\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed53.sh submitted!
job id: 45221402
54
2022-10-29 08:08:07 b'Submitted batch job 45221403\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed54.sh submitted!
job id: 45221403
55
2022-10-29 08:08:07 b'Submitted batch job 45221404\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed55.sh submitted!
job id: 45221404
56
2022-10-29 08:08:08 b'Submitted batch job 45221405\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed56.sh submitted!
job id: 45221405
57
2022-10-29 08:08:08 b'Submitted batch job 45221406\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed57.sh submitted!
job id: 45221406
58
2022-10-29 08:08:09 b'Submitted batch job 45221407\n' None
/pool001/shibal/results-synthetic/bashes/v13_n100_r1.5/seed58.sh submitted!
job id: 45221407
59
2022-10-29 08:08:09 b'Submitted batch job 45221408\n' None
/pool001/sh

In [ ]:
from subprocess import Popen, PIPE

In [155]:
for job in range(45069627, 45069643):
    process = Popen(['scancel',str(job)], stdout=PIPE)
    (output, err) = process.communicate()
    exit_code = process.wait()
    if exit_code ==0:
        print(job, "deleted!")

45069627 deleted!
45069628 deleted!
45069629 deleted!
45069630 deleted!
45069631 deleted!
45069632 deleted!
45069633 deleted!
45069634 deleted!
45069635 deleted!
45069636 deleted!
45069637 deleted!
45069638 deleted!
45069639 deleted!
45069640 deleted!
45069641 deleted!
45069642 deleted!


In [214]:
for seed in range(100):
    command = f"""rm -r /pool001/shibal/results-synthetic/N_train_100/seed{seed}/AMsWithInteractionsStrongHierarchy/v12/r1.0"""
    print(command)
    !{command}

rm -r /pool001/shibal/results-synthetic/N_train_100/seed0/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed1/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed2/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed3/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed4/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed5/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed6/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed7/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed8/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed9/AMsWithInteractionsStron

rm -r /pool001/shibal/results-synthetic/N_train_100/seed80/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed81/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed82/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed83/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed84/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed85/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed86/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed87/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed88/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed89/AMsWithInterac

In [1]:
import numpy as np

In [93]:
vals = []
MISE = []
mains = []
interactions = []
fprs_main = []
fnrs_main = []
f1s_main = []
fprs_interaction = []
fnrs_interaction = []
f1s_interaction = []


for seed in np.arange(100):
    filename = '/pool001/shibal/results-synthetic/N_train_1000/seed{}/AMsWithInteractionsStrongHierarchy/v13/r1.5'.format(seed)
    
    try:
        with open(filename+'/Results-HS.txt') as file:
            lines = file.readlines()
            val = float([line for line in lines if "val" in line][0].split("val: ")[1].split(",")[0])
            vals.append(val)
            mise = float([line for line in lines if "True" in line][0].split(" ")[-1].split("\n")[0])
            MISE.append(mise)
            fpr_main = float([line for line in lines if "FPR (main)" in line][0].split(" ")[-1].split("\n")[0])
            fprs_main.append(fpr_main)
            fnr_main = float([line for line in lines if "FNR (main)" in line][0].split(" ")[-1].split("\n")[0])
            fnrs_main.append(fnr_main)
            f1_main = float([line for line in lines if "F1 (main)" in line][0].split(" ")[-1].split("\n")[0])
            f1s_main.append(f1_main)
            fpr_interaction = float([line for line in lines if "FPR (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            fprs_interaction.append(fpr_interaction)
            fnr_interaction = float([line for line in lines if "FNR (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            fnrs_interaction.append(fnr_interaction)
            f1_interaction = float([line for line in lines if "F1 (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            f1s_interaction.append(f1_interaction)
            print("Seed: ", seed, " mise:", mise)
            
        with open(filename+'/support_set.npy', 'rb') as f:
            main_set = np.load(f)
            interaction_set = np.load(f)
            mains.append(main_set)
            interactions.append(interaction_set)
    except:
        print("Seed: ", seed, "Not found")

Seed:  0  mise: 0.011713149340407375
Seed:  1  mise: 0.020420459946475594
Seed:  2  mise: 0.010355183527421334
Seed:  3  mise: 0.014352283879677939
Seed:  4  mise: 0.008491883886866043
Seed:  5  mise: 0.008862362145325292
Seed:  6  mise: 0.015285636911597839
Seed:  7  mise: 0.011143714250096434
Seed:  8  mise: 0.015861748580692198
Seed:  9  mise: 0.016652094427319786
Seed:  10  mise: 0.01179077518458568
Seed:  11  mise: 0.017046996364787573
Seed:  12  mise: 0.010730212903529374
Seed:  13  mise: 0.013497935493256888
Seed:  14  mise: 0.01717196980799719
Seed:  15  mise: 0.011450639709545896
Seed:  16  mise: 0.017781245815027637
Seed:  17  mise: 0.022071836166931886
Seed:  18  mise: 0.01425223400413779
Seed:  19  mise: 0.011341548644678668
Seed:  20  mise: 0.010233284218581943
Seed:  21  mise: 0.014675347370965118
Seed:  22  mise: 0.013416339923320121
Seed:  23  mise: 0.011863427939847555
Seed:  24  mise: 0.015463826706472424
Seed:  25  mise: 0.013270921005814725
Seed:  26  mise: 0.009767

In [94]:
len(MISE)

100

In [95]:
np.median(MISE)

0.013343630464567423

In [96]:
print("val:", np.mean(vals), "std-err:", np.std(vals)/np.sqrt(len(vals)))
print("MISE:", np.mean(MISE), "std-err:", np.std(MISE)/np.sqrt(len(MISE)))
print("FPR (main):", np.mean(fprs_main), "std-err:", np.std(fprs_main)/np.sqrt(len(fprs_main)))
print("FNR (main):", np.mean(fnrs_main), "std-err:", np.std(fnrs_main)/np.sqrt(len(fnrs_main)))
print("F1 (main):", np.mean(f1s_main), "std-err:", np.std(f1s_main)/np.sqrt(len(f1s_main)))
print("FPR (interactions):", np.mean(fprs_interaction), "std-err:", np.std(fprs_interaction)/np.sqrt(len(fprs_interaction)))
print("FNR (interactions):", np.mean(fnrs_interaction), "std-err:", np.std(fnrs_interaction)/np.sqrt(len(fnrs_interaction)))
print("F1 (interactions):", np.mean(f1s_interaction), "std-err:", np.std(f1s_interaction)/np.sqrt(len(f1s_interaction)))


val: 0.07870474000000001 std-err: 0.00037692249485006855
MISE: 0.013843630833964615 std-err: 0.0003772733635629191
FPR (main): 0.0016666666666666663 std-err: 0.0016583123951777
FNR (main): 0.0 std-err: 0.0
F1 (main): 0.9988888888888888 std-err: 0.0011055415967851322
FPR (interactions): 0.0011904761904761919 std-err: 0.0006185895741317425
FNR (interactions): 0.013333333333333334 std-err: 0.006531972647421809
F1 (interactions): 0.9852142857142857 std-err: 0.005117252730733951


In [97]:
np.unique(np.concatenate(mains).ravel(), return_counts=True)

(array([0, 1, 2, 3, 7]), array([100, 100, 100, 100,   1]))

In [98]:
interactions = [inter for inter in interactions if len(inter)>0]
np.unique(np.concatenate(interactions, axis=0), return_counts=True, axis=0)

(array([[0, 1],
        [0, 2],
        [0, 7],
        [1, 3],
        [2, 3],
        [3, 7]]),
 array([100, 100,   1,   3,  96,   1]))