In [7]:
import numpy as np
import pandas as pd
import os
import shutil
from subprocess import Popen, PIPE
from IPython.display import clear_output
import time

In [239]:
PYPATH = '/home/shibal/anaconda3/envs/jasa/bin/python'
FILEPATH = '/home/shibal/Additive-Models-with-Structured-Interactions/SparseAMsWithInteractions/src/AMsWithInteractionsStrongHierarchy/AMsWithInteractionsStrongHierarchy-Synthetic-CV.py'
PATH = "/pool001/shibal/results-synthetic"

version = 13
n = 400
r = 1.0

In [240]:
def make_bash_file(seed, version, n, r):
    bash_folder_path = f"{PATH}/bashes/v{version}_n{n}_r{r}"
    bash_file_path = os.path.join(bash_folder_path, "seed{}.sh".format(seed))
    log_path = f"{PATH}/logs/v{version}_n{n}_r{r}/seed{seed}"
    os.makedirs(bash_folder_path,exist_ok=True)
    os.makedirs(log_path,exist_ok=True)
    with open(bash_file_path,"w") as f:
        f.write("#!/bin/bash\n")
        f.write("#SBATCH --cpus-per-task=4\n")
        f.write("#SBATCH --time=4-00:00\n")
        f.write("#SBATCH --mem=16G\n")
        f.write("#SBATCH -p sched_mit_sloan_batch\n")        
        f.write("#SBATCH --mail-type=FAIL\n")
        f.write("#SBATCH --mail-user=shibal@mit.edu\n")
        f.write(f"#SBATCH -o {log_path}/seed{seed}_%j.out\n")
        f.write(f"#SBATCH -e {log_path}/_seed{seed}_%j.err\n\n")
        f.write("module load sloan/python/modules/python-3.6/gurobipy/9.0.1\n\n")
        f.write(f"{PYPATH} -u {FILEPATH}  --seed {seed} --train_size {n} --version {version} --r {r} |& tee -a {log_path}/output.txt") 
    return bash_file_path


In [241]:
bash_files = []
seeds = np.arange(95,100)
for seed in seeds:
    bash_files.append(make_bash_file(seed, version, n, r))

In [242]:
torun = seeds
# torun = range(1,6)
submitted = []
print(len(torun))

100


In [243]:
exit_code = 1
for i, seed in enumerate(seeds):
    if i % 100 == 0:
        clear_output(wait=True)
    print(i)
    sh = make_bash_file(seed, version, n, r)
    while True:
        process = Popen(["sbatch",sh], stdout=PIPE)
        (output, err) = process.communicate()
        exit_code = process.wait()
        print(time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time())),output,err)
        if exit_code == 0:
            print(sh,"submitted!")
            tmp_id = str(output)[-11:-3]
            print("job id:", tmp_id)
            submitted.append(tmp_id)
            break
        time.sleep(10000)

0
2022-10-28 07:26:53 b'Submitted batch job 45144293\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed0.sh submitted!
job id: 45144293
1
2022-10-28 07:26:53 b'Submitted batch job 45144295\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed1.sh submitted!
job id: 45144295
2
2022-10-28 07:26:54 b'Submitted batch job 45144296\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed2.sh submitted!
job id: 45144296
3
2022-10-28 07:26:54 b'Submitted batch job 45144297\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed3.sh submitted!
job id: 45144297
4
2022-10-28 07:26:55 b'Submitted batch job 45144298\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed4.sh submitted!
job id: 45144298
5
2022-10-28 07:26:55 b'Submitted batch job 45144299\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed5.sh submitted!
job id: 45144299
6
2022-10-28 07:26:55 b'Submitted batch job 45144300\n' None
/pool001/shibal/resul

2022-10-28 07:27:08 b'Submitted batch job 45144347\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed53.sh submitted!
job id: 45144347
54
2022-10-28 07:27:09 b'Submitted batch job 45144348\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed54.sh submitted!
job id: 45144348
55
2022-10-28 07:27:09 b'Submitted batch job 45144349\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed55.sh submitted!
job id: 45144349
56
2022-10-28 07:27:09 b'Submitted batch job 45144350\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed56.sh submitted!
job id: 45144350
57
2022-10-28 07:27:09 b'Submitted batch job 45144351\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed57.sh submitted!
job id: 45144351
58
2022-10-28 07:27:10 b'Submitted batch job 45144352\n' None
/pool001/shibal/results-synthetic/bashes/v13_n400_r1.0/seed58.sh submitted!
job id: 45144352
59
2022-10-28 07:27:10 b'Submitted batch job 45144353\n' None
/pool001/sh

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/home/shibal/anaconda3/envs/jasa/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-243-ba51ac46df20>", line 18, in <module>
    time.sleep(10000)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shibal/anaconda3/envs/jasa/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shibal/anaconda3/envs/jasa/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-243-ba51ac46df20>'

During handling of 

TypeError: object of type 'NoneType' has no len()

In [ ]:
from subprocess import Popen, PIPE

In [155]:
for job in range(45069627, 45069643):
    process = Popen(['scancel',str(job)], stdout=PIPE)
    (output, err) = process.communicate()
    exit_code = process.wait()
    if exit_code ==0:
        print(job, "deleted!")

45069627 deleted!
45069628 deleted!
45069629 deleted!
45069630 deleted!
45069631 deleted!
45069632 deleted!
45069633 deleted!
45069634 deleted!
45069635 deleted!
45069636 deleted!
45069637 deleted!
45069638 deleted!
45069639 deleted!
45069640 deleted!
45069641 deleted!
45069642 deleted!


In [214]:
for seed in range(100):
    command = f"""rm -r /pool001/shibal/results-synthetic/N_train_100/seed{seed}/AMsWithInteractionsStrongHierarchy/v12/r1.0"""
    print(command)
    !{command}

rm -r /pool001/shibal/results-synthetic/N_train_100/seed0/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed1/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed2/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed3/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed4/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed5/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed6/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed7/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed8/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed9/AMsWithInteractionsStron

rm -r /pool001/shibal/results-synthetic/N_train_100/seed80/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed81/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed82/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed83/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed84/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed85/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed86/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed87/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed88/AMsWithInteractionsStrongHierarchy/v12/r1.0
rm -r /pool001/shibal/results-synthetic/N_train_100/seed89/AMsWithInterac

In [23]:
import numpy as np

In [213]:
MISE = []
mains = []
interactions = []
fprs_main = []
fnrs_main = []
f1s_main = []
fprs_interaction = []
fnrs_interaction = []
f1s_interaction = []


for seed in np.arange(100):
    filename = '/pool001/shibal/results-synthetic/N_train_400/seed{}/AMsWithInteractionsStrongHierarchy/v12/r1.5'.format(seed)
    
    try:
        with open(filename+'/Results-HS.txt') as file:
            lines = file.readlines()
            mise = float([line for line in lines if "True" in line][0].split(" ")[-1].split("\n")[0])
            MISE.append(mise)
            fpr_main = float([line for line in lines if "FPR (main)" in line][0].split(" ")[-1].split("\n")[0])
            fprs_main.append(fpr_main)
            fnr_main = float([line for line in lines if "FNR (main)" in line][0].split(" ")[-1].split("\n")[0])
            fnrs_main.append(fnr_main)
            f1_main = float([line for line in lines if "F1 (main)" in line][0].split(" ")[-1].split("\n")[0])
            f1s_main.append(f1_main)
            fpr_interaction = float([line for line in lines if "FPR (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            fprs_interaction.append(fpr_interaction)
            fnr_interaction = float([line for line in lines if "FNR (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            fnrs_interaction.append(fnr_interaction)
            f1_interaction = float([line for line in lines if "F1 (interactions)" in line][0].split(" ")[-1].split("\n")[0])
            f1s_interaction.append(f1_interaction)
            print("Seed: ", seed, " mise:", mise)
            
        with open(filename+'/support_set.npy', 'rb') as f:
            main_set = np.load(f)
            interaction_set = np.load(f)
            mains.append(main_set)
            interactions.append(interaction_set)
    except:
        pass

In [ ]:
len(MISE)

In [211]:
np.median(MISE)

/home/shibal/anaconda3/envs/jasa/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/shibal/anaconda3/envs/jasa/lib/python3.6/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [178]:
print("MISE:", np.mean(MISE), "std-err:", np.std(MISE)/np.sqrt(len(MISE)))
print("FPR (main):", np.mean(fprs_main), "std-err:", np.std(fprs_main)/np.sqrt(len(fprs_main)))
print("FNR (main):", np.mean(fnrs_main), "std-err:", np.std(fnrs_main)/np.sqrt(len(fnrs_main)))
print("F1 (main):", np.mean(f1s_main), "std-err:", np.std(f1s_main)/np.sqrt(len(f1s_main)))
print("FPR (interactions):", np.mean(fprs_interaction), "std-err:", np.std(fprs_interaction)/np.sqrt(len(fprs_interaction)))
print("FNR (interactions):", np.mean(fnrs_interaction), "std-err:", np.std(fnrs_interaction)/np.sqrt(len(fnrs_interaction)))
print("F1 (interactions):", np.mean(f1s_interaction), "std-err:", np.std(f1s_interaction)/np.sqrt(len(f1s_interaction)))


MISE: 0.050922325140178935 std-err: 0.0061614350605426445
FPR (main): 0.006734006734006734 std-err: 0.00528050473222291
FNR (main): 0.020202020202020204 std-err: 0.007723118706483095
F1 (main): 0.9840978325826811 std-err: 0.005488585525612171
FPR (interactions): 0.001924001924001925 std-err: 0.0009423662235774552
FNR (interactions): 0.15824915824915828 std-err: 0.020393833688234244
F1 (interactions): 0.8888648388648388 std-err: 0.014151465290720134


In [133]:
np.unique(np.concatenate(mains).ravel(), return_counts=True)

(array([0, 1, 2, 3, 4]), array([98, 98, 98, 98,  1]))

In [134]:
interactions = [inter for inter in interactions if len(inter)>0]
np.unique(np.concatenate(interactions, axis=0), return_counts=True, axis=0)

(array([[0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 3],
        [2, 3],
        [2, 4]]),
 array([98, 98,  3,  1,  3, 94,  1]))